keys:
  - &main   7D2F4C6B9A8300CCDDB641FDDF14B55A7A29C30F
  - &victim age1ndhan47vrgs736m0xgnj2tv5r242annemkugvxf7tkd87wlgvsvqzhqdd9

creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *main
      age:
      - *victim
